param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectId,

    [Parameter(Mandatory = $true)]
    [string]$Title,

    [Parameter(Mandatory = $true)]
    [string]$Type,

    [string]$Description,
    [string]$AssignedTo,
    [int]$ParentId,
    [string]$IterationPath,
    [string]$BaseUrl = "http://localhost:8181"
)

$ErrorActionPreference = "Stop"

$base = $BaseUrl.TrimEnd("/")

$azdoOrg = $env:AZDO_ORG
$azdoPat = $env:AZDO_PAT

if ([string]::IsNullOrWhiteSpace($azdoOrg)) {
    throw 'Missing AZDO_ORG environment variable. Set it with: setx AZDO_ORG "my-organization"; then restart the terminal/Codex session.'
}

if ([string]::IsNullOrWhiteSpace($azdoPat)) {
    throw 'Missing AZDO_PAT environment variable. Set it with: setx AZDO_PAT "<pat>"; then restart the terminal/Codex session. Do not paste the PAT into chat.'
}

$headers = @{
    "X-Azdo-Org" = $azdoOrg.Trim()
    "X-Azdo-Pat" = $azdoPat.Trim()
}

try {
    Invoke-RestMethod -Method Get -Uri "$base/api/health" | Out-Null
}
catch {
    throw "Sprintly backend is not reachable at $base. Start it from backend with: dotnet run"
}

$body = [ordered]@{
    title = $Title
    type = $Type
    description = $null
    assignedTo = $null
    parentId = $null
    iterationPath = $null
}

if (-not [string]::IsNullOrWhiteSpace($Description)) {
    $stampedDescription = $Description
    if ($stampedDescription -notmatch "\[Generated by AI\]") {
        if ($stampedDescription -match '<[a-zA-Z/][^>]*>') {
            $stampedDescription = "$stampedDescription<br><br><div>[Generated by AI]</div>"
        }
        else {
            $stampedDescription = "$stampedDescription`n`n[Generated by AI]"
        }
    }
    $body.description = $stampedDescription
}
if (-not [string]::IsNullOrWhiteSpace($AssignedTo)) { $body.assignedTo = $AssignedTo }
if ($ParentId -gt 0) { $body.parentId = $ParentId }
if (-not [string]::IsNullOrWhiteSpace($IterationPath)) { $body.iterationPath = $IterationPath }

$json = $body | ConvertTo-Json -Depth 8
$project = [System.Uri]::EscapeDataString($ProjectId)
$created = Invoke-RestMethod `
    -Method Post `
    -Uri "$base/api/projects/$project/workitems" `
    -Headers $headers `
    -ContentType "application/json" `
    -Body $json

$created | ConvertTo-Json -Depth 8
